name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./env/prd
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name : Configure AWS credentials
        uses : aws-actions/configure-aws-credentials@v2
        with :
          aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET_KEY }}
          aws-region : ap-northeast-2

      - name : Terraform Init
        run : terraform init

      - name : Terraform Validate
        run : terraform validate

      - name : Terraform Plan
        run : terraform plan -var-file=terraform.tfvars -lock=false